version: "3.8"
services: 
  website:
    build: ./calendify
    ports: 
      - 8080:8080
    volumes: 
      - ./calendify/src:/calendify/src
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase